In [1]:
import dynamic_traffic_signal
import importlib

In [2]:
a = dynamic_traffic_signal.DynamicTrafficSignal('Testing_class_ijipura_small')

In [3]:
minlat="12.9380131671"
minlon="77.6319900345" 
maxlat="12.939314082" 
maxlon="77.6337735827"

In [6]:
a.get_map(minlon,minlat, maxlon,  maxlat)
a.build_traffic()
a.optimize_traffic_lights(timing_range={'min':15,'max':16}, gui=False)

Input traffic value for each road passing the junction: cluster_315208341_315208342


ValueError: cannot call `vectorize` on size 0 inputs unless `otypes` is set

In [6]:
from scipy.optimize import brute

def f(x):
    print('JJJ')
    if x < 1:
        return 10
    return x**2 - 0.1

x0, fval, grid, Jout = brute(f, ranges=((-3,3),), full_output=True, finish=None)

print(fval)
print(type(fval))

x0, fval, grid, Jout = brute(f, ranges=((-3,3),), full_output=True)

print(fval)
print(type(fval))

JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
1
<class 'numpy.int64'>
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
0.9000513986867548
<class 'numpy.float64'>


In [6]:
x0

array([1.0000257])

In [7]:
grid

array([-3.        , -2.68421053, -2.36842105, -2.05263158, -1.73684211,
       -1.42105263, -1.10526316, -0.78947368, -0.47368421, -0.15789474,
        0.15789474,  0.47368421,  0.78947368,  1.10526316,  1.42105263,
        1.73684211,  2.05263158,  2.36842105,  2.68421053,  3.        ])

In [8]:
((-3,3),)

((-3, 3),)

In [9]:
Jout

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  1,  1,  2,  4,
        5,  7,  8])

In [11]:
[(i+1)*30 for i in range(3)]

[30, 60, 90]

In [16]:
import numpy as np
a=[30, 30, 30]

np.cumsum(a).tolist()

[30, 60, 90]

In [13]:
import pandas as pd
import requests, json
import numpy as np
import folium
import re

In [14]:
minlon, minlat, maxlon, maxlat = 77.7519486464,12.9833797192,77.7528560462,12.9842016832

minlat=str(minlat)
minlon=str(minlon)
maxlat=str(maxlat)
maxlon=str(maxlon)

In [15]:
def create_data_1(dictionary):
        import datetime
        RWS=dictionary['RWS']
        l=[]
        for rw in RWS:
            EBU_COUNTRY_CODE=rw['EBU_COUNTRY_CODE']
            EXTENDED_COUNTRY_CODE=rw['EXTENDED_COUNTRY_CODE']
            UNITS=rw['UNITS']
            for elem in rw['RW']:
                DE=elem['DE']
                LI=elem['LI']
                PBT=elem['PBT']
                mid=elem['mid']
                FIS=elem['FIS']
                for FI in FIS:
                    elem_1=FI['FI']
                    for elem_2 in elem_1:
                        LE=elem_2['TMC']['LE']
                        PC=elem_2['TMC']['PC']
                        QD=elem_2['TMC']['QD']
                        SHP=elem_2['SHP']
                        CF=elem_2['CF']
                        for elem_3 in CF:
                            FF=elem_3['FF']
                            CN=elem_3['CN']                    
                            JF=elem_3['JF']
                            SP=elem_3['SP']
                            TY=elem_3['TY']
                            l.append([EBU_COUNTRY_CODE,EXTENDED_COUNTRY_CODE,UNITS,DE,LI,PBT,mid,LE,PC,QD,SHP,FF,CN,JF,SP,TY])
        clms=['EBU_COUNTRY_CODE','EXTENDED_COUNTRY_CODE','UNITS','DE','LI','PBT','mid','LE','PC','QD','SHP','FF','CN','JF','SP','TY']                    
        df=pd.DataFrame(l,columns=clms)
        df['PBT']=datetime.datetime.now()
        #print(json.dumps(rws_list, indent=2))
    #     if path_to_save:
    #         if os.path.isfile(path_to_save):
    #             df.to_csv(path_to_save,mode='a+',header=False,index=False)
    #         else:
    #             df.to_csv(path_to_save,mode='w+',index=False)
    #     else:
        return df   

In [23]:
#state='New Castle'
def search(keyword=""):
    endpoint = "search"
    attribute_string = "?keyword="+keyword

    r = get_results(endpoint, attribute_string)
    return r

def get_results( endpoint="", attribute_string=""):
    url_with_attr = geo_code_url+endpoint+attribute_string
    r = requests.get(url_with_attr, auth=HTTPBasicAuth('geocode', 'ZXasqw12'))
    if r.status_code == 200:
        if r.text == "":
            return "nil"
        else:
            return r.json()
    else:
        return r

from requests.auth import HTTPBasicAuth
geo_code_url = "https://opendata-maps.herokuapp.com/api/geocode/"

def get_realtime_data():
    #pos=search(state)
    #bbox_bangalore=pos['result']['results'][0]['geometry']['bounds']


    ori='https://traffic.cit.api.here.com/traffic/6.1/flow.json?bbox='+minlat\
    +'%2C'+minlon+'%3B'+maxlat+'%2C'+maxlon\
    +'&responseattributes=sh,fc&app_code=JX9Bh_OK-4u3zQSHxqjOkA&app_id=C0j2ZeJpgkm71fOJGGzv'


    ori=requests.get(ori)
    ori_json = ori.json()
    ori=create_data_1(ori.json())
    return ori, ori_json

In [24]:
data, j_data = get_realtime_data()
data['SHP'] = data['SHP'].astype(str)
data

EBU_COUNTRY_CODE EXTENDED_COUNTRY_CODE   UNITS                DE         LI  \
0                5                    F2  metric            NH-207  503+01830   
1                5                    F2  metric            NH-207  503-01830   
2                5                    F2  metric  White Field Road  503-02567   
3                5                    F2  metric  White Field Road  503-02567   
4                5                    F2  metric  White Field Road  503+02567   
5                5                    F2  metric  White Field Road  503+02567   

                         PBT                                    mid       LE  \
0 2018-06-22 18:11:51.442470  1139a1fd-641f-4994-b182-bda126a344e8|  3.26892   
1 2018-06-22 18:11:51.442470  53dd56cf-f0e0-44b6-9f0a-662541ea18c6|  3.26879   
2 2018-06-22 18:11:51.442470  2e247b36-a678-4708-a632-91bedd35c431|  1.04761   
3 2018-06-22 18:11:51.442470  2e247b36-a678-4708-a632-91bedd35c431|  2.09788   
4 2018-06-22 18:11:51.442470  19edbe9f-5c9a-4837-8359-a49a7a972375|  2.12029   
5 2018-06-22 18:11:51.442470  19edbe9f-5c9a-4837-8359-a49a7a972375|  1.05208   

     PC QD                                                SHP    FF    CN  \
0  1836  -  [{'FC': 3, 'value': ['12.96984,77.74992 12.970...  36.0  0.71   
1  1835  +  [{'FC': 3, 'value': ['12.99774,77.75833 12.997...  36.0  0.70   
2  2572  +  [{'FC': 3, 'value': ['12.98295,77.76181 12.982...  27.0  0.70   
3  2571  +  [{'FC': 3, 'value': ['12.98373,77.75242 12.983...  35.0  0.70   
4  2572  -  [{'FC': 3, 'value': ['12.98792,77.73363 12.987...  39.0  0.71   
5  2573  -  [{'FC': 3, 'value': ['12.9838,77.75254 12.9837...  35.0  0.70   

        JF     SP  TY  
0  5.64824  19.08  TR  
1  5.27712  20.00  TR  
2  5.41091  13.99  TR  
3  8.10438  12.00  TR  
4  7.64053  15.54  TR  
5  5.83905  18.00  TR

In [25]:
def traffic_map_across_city_historical(traffic_data):
    
    traffic_hour= traffic_data
    df_jaipur=traffic_data
    df_ori=df_jaipur
    list_shp = df_jaipur['SHP'].unique()
    list_mean = []
    start_point=[]
    end_point=[]
    for s in list_shp:
        tmp = re.findall("[+-]?\d*\.\d+", s)
        #print(tmp)
        tmp=[float(i) for i in tmp]
        tmp2 = []
        it = iter(tmp)
        for z in it:
            tmp2.append([z, next(it)])
        a = np.array(tmp2)
        list_mean.append(list(np.mean(a, axis=0)))
        start_point.append(tmp2[0])
        end_point.append(tmp2[-1])
    df_t = pd.DataFrame()
    df_t['SHP'] = list_shp
    df_t['mean'] = list_mean
    df_final =df_jaipur.merge(df_t,on='SHP')
    df_final['latitude'] = np.array(df_final['mean'].values.tolist())[:,0]
    df_final['longitude'] = np.array(df_final['mean'].values.tolist())[:,1]
    hh=pd.pivot_table(df_final,index=['SHP','PC','DE'],values='JF',aggfunc='median').reset_index()
    da1=hh.sort_values('JF',ascending=False)
    #da2=da1[da1['JF']>5]
    da2=da1

    data_2=da2
    data_2=data_2
    import branca.colormap as cm

    colormap = cm.LinearColormap(['green','yellow','red'],vmin=0,vmax=10)
    colormap.caption="Jamfactor_levels"
#     lat_long=df[['latitude','longitude']].values[0].tolist()
    x=folium.Map(location=[12.9380131671,77.6319900345],zoom_start=10)
    # x

    for i in data_2.index.tolist():
        color_grad_val=data_2['JF'][i]
        tmp2=[]
        #tmp=re.findall("\d*\.\d+", data_2['SHP'][i])
        tmp = re.findall("[+-]?\d*\.\d+", data_2['SHP'][i])
        #print(tmp)
        tmp=[float(i) for i in tmp]

        it = iter(tmp)
        for z in it:
            tmp2.append([z, next(it)])
        y=folium.PolyLine(locations=tmp2,color=colormap.rgb_hex_str(color_grad_val),opacity=0.75,weight=7)
        x.add_children(y)
        
    
    df= df_final[['latitude','longitude','PC']].drop_duplicates()

    l = df[['latitude','longitude']].values.tolist()

    #map_osm = folium.Map(location=[38.946241233265095, -77.04115322627564],tiles='CartoDB Positron',
    #                     zoom_start=12)
    for i,k in zip(l,df['PC']):

        marker = folium.Marker(i,popup=str(k),icon=folium.Icon())

        x.add_child(marker)

    

    x
    display(x)

In [26]:
traffic_map_across_city_historical(data)

/home/eudie/.virtualenvs/Traffic_Simulation/lib/python3.5/site-packages/ipykernel_launcher.py:55: FutureWarning: Method `add_children` is deprecated. Please use `add_child` instead.


In [27]:
j_data

{'CREATED_TIMESTAMP': '2018-06-22T12:40:49.000+0000',
 'MAP_VERSION': '',
 'RWS': [{'EBU_COUNTRY_CODE': '5',
   'EXTENDED_COUNTRY_CODE': 'F2',
   'MAP_VERSION': '201802',
   'RW': [{'DE': 'NH-207',
     'FIS': [{'FI': [{'CF': [{'CN': 0.71,
           'FF': 36.0,
           'JF': 5.64824,
           'SP': 19.08,
           'SU': 19.08,
           'TY': 'TR'}],
         'SHP': [{'FC': 3, 'value': ['12.96984,77.74992 12.97022,77.74997 ']},
          {'FC': 3, 'value': ['12.97022,77.74997 12.9703,77.74998 ']},
          {'FC': 3, 'value': ['12.9703,77.74998 12.9704,77.75 ']},
          {'FC': 3, 'value': ['12.9704,77.75 12.97075,77.75006 ']},
          {'FC': 3, 'value': ['12.97075,77.75006 12.97083,77.75007 ']},
          {'FC': 3, 'value': ['12.97083,77.75007 12.97092,77.75008 ']},
          {'FC': 3, 'value': ['12.97092,77.75008 12.97102,77.75009 ']},
          {'FC': 3, 'value': ['12.97102,77.75009 12.97143,77.75014 ']},
          {'FC': 3, 'value': ['12.97143,77.75014 12.97202,77.7502

In [28]:
data

EBU_COUNTRY_CODE EXTENDED_COUNTRY_CODE   UNITS                DE         LI  \
0                5                    F2  metric            NH-207  503+01830   
1                5                    F2  metric            NH-207  503-01830   
2                5                    F2  metric  White Field Road  503-02567   
3                5                    F2  metric  White Field Road  503-02567   
4                5                    F2  metric  White Field Road  503+02567   
5                5                    F2  metric  White Field Road  503+02567   

                         PBT                                    mid       LE  \
0 2018-06-22 18:11:51.442470  1139a1fd-641f-4994-b182-bda126a344e8|  3.26892   
1 2018-06-22 18:11:51.442470  53dd56cf-f0e0-44b6-9f0a-662541ea18c6|  3.26879   
2 2018-06-22 18:11:51.442470  2e247b36-a678-4708-a632-91bedd35c431|  1.04761   
3 2018-06-22 18:11:51.442470  2e247b36-a678-4708-a632-91bedd35c431|  2.09788   
4 2018-06-22 18:11:51.442470  19edbe9f-5c9a-4837-8359-a49a7a972375|  2.12029   
5 2018-06-22 18:11:51.442470  19edbe9f-5c9a-4837-8359-a49a7a972375|  1.05208   

     PC QD                                                SHP    FF    CN  \
0  1836  -  [{'FC': 3, 'value': ['12.96984,77.74992 12.970...  36.0  0.71   
1  1835  +  [{'FC': 3, 'value': ['12.99774,77.75833 12.997...  36.0  0.70   
2  2572  +  [{'FC': 3, 'value': ['12.98295,77.76181 12.982...  27.0  0.70   
3  2571  +  [{'FC': 3, 'value': ['12.98373,77.75242 12.983...  35.0  0.70   
4  2572  -  [{'FC': 3, 'value': ['12.98792,77.73363 12.987...  39.0  0.71   
5  2573  -  [{'FC': 3, 'value': ['12.9838,77.75254 12.9837...  35.0  0.70   

        JF     SP  TY  
0  5.64824  19.08  TR  
1  5.27712  20.00  TR  
2  5.41091  13.99  TR  
3  8.10438  12.00  TR  
4  7.64053  15.54  TR  
5  5.83905  18.00  TR