In [1]:
import dynamic_traffic_signal
import importlib

In [2]:
a = dynamic_traffic_signal.DynamicTrafficSignal('Testing_class_ijipura_small')

In [3]:
minlat="12.9380131671"
minlon="77.6319900345" 
maxlat="12.939314082" 
maxlon="77.6337735827"

In [6]:
a.get_map(minlon,minlat, maxlon,  maxlat)
a.build_traffic()
a.optimize_traffic_lights(timing_range={'min':5,'max':20}, gui=False)

Input traffic value for each road passing the junction: cluster_315208341_315208342
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds


{'junction': 'cluster_315208341_315208342',
 'phases': ['GGGGrrrrrrrrrrrrrr',
  'rrrrGGGGGrrrrrrrrr',
  'rrrrrrrrrGGGGrrrrr',
  'rrrrrrrrrrrrrGGGGG'],
 'time': [5.0, 10.0, 15.0, 20.0]}

In [5]:
from scipy.optimize import brute

def f(x):
    if x < 1:
        return 10
    return x**2 - 0.1

x0, fval, grid, Jout = brute(f, ranges=((-3,3),), full_output=True, finish=None)

print(fval)
print(type(fval))

x0, fval, grid, Jout = brute(f, ranges=((-3,3),), full_output=True)

print(fval)
print(type(fval))

1
<class 'numpy.int64'>
0.9000513986867548
<class 'numpy.float64'>


In [6]:
x0

array([1.0000257])

In [7]:
grid

array([-3.        , -2.68421053, -2.36842105, -2.05263158, -1.73684211,
       -1.42105263, -1.10526316, -0.78947368, -0.47368421, -0.15789474,
        0.15789474,  0.47368421,  0.78947368,  1.10526316,  1.42105263,
        1.73684211,  2.05263158,  2.36842105,  2.68421053,  3.        ])

In [8]:
((-3,3),)

((-3, 3),)

In [9]:
Jout

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  1,  1,  2,  4,
        5,  7,  8])

In [11]:
[(i+1)*30 for i in range(3)]

[30, 60, 90]

In [16]:
import numpy as np
a=[30, 30, 30]

np.cumsum(a).tolist()

[30, 60, 90]

In [7]:
[(1,2)]*3

[(1, 2), (1, 2), (1, 2)]