In [1]:
import dynamic_traffic_signal
import importlib

In [2]:
a = dynamic_traffic_signal.DynamicTrafficSignal('Testing_class_ijipura_small')

In [3]:
minlat="12.9380131671"
minlon="77.6319900345" 
maxlat="12.939314082" 
maxlon="77.6337735827"

In [5]:
a.get_map(minlon,minlat, maxlon,  maxlat)
a.build_traffic()
a.optimize_traffic_lights(timing_range={'min':15,'max':17}, gui=False)

Input traffic value for each road passing the junction: cluster_315208341_315208342
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds
 Retrying in 1 seconds


KeyboardInterrupt: 

In [6]:
from scipy.optimize import brute

def f(x):
    print('JJJ')
    if x < 1:
        return 10
    return x**2 - 0.1

x0, fval, grid, Jout = brute(f, ranges=((-3,3),), full_output=True, finish=None)

print(fval)
print(type(fval))

x0, fval, grid, Jout = brute(f, ranges=((-3,3),), full_output=True)

print(fval)
print(type(fval))

JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
1
<class 'numpy.int64'>
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
JJJ
0.9000513986867548
<class 'numpy.float64'>


In [6]:
x0

array([1.0000257])

In [7]:
grid

array([-3.        , -2.68421053, -2.36842105, -2.05263158, -1.73684211,
       -1.42105263, -1.10526316, -0.78947368, -0.47368421, -0.15789474,
        0.15789474,  0.47368421,  0.78947368,  1.10526316,  1.42105263,
        1.73684211,  2.05263158,  2.36842105,  2.68421053,  3.        ])

In [8]:
((-3,3),)

((-3, 3),)

In [9]:
Jout

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  1,  1,  2,  4,
        5,  7,  8])

In [11]:
[(i+1)*30 for i in range(3)]

[30, 60, 90]

In [16]:
import numpy as np
a=[30, 30, 30]

np.cumsum(a).tolist()

[30, 60, 90]

In [7]:
minlat="12.9380131671"
minlon="77.6319900345" 
maxlat="12.939314082" 
maxlon="77.6337735827"

[(1, 2), (1, 2), (1, 2)]

In [8]:
def create_data_1(dictionary):
        import datetime
        RWS=dictionary['RWS']
        l=[]
        for rw in RWS:
            EBU_COUNTRY_CODE=rw['EBU_COUNTRY_CODE']
            EXTENDED_COUNTRY_CODE=rw['EXTENDED_COUNTRY_CODE']
            UNITS=rw['UNITS']
            for elem in rw['RW']:
                DE=elem['DE']
                LI=elem['LI']
                PBT=elem['PBT']
                mid=elem['mid']
                FIS=elem['FIS']
                for FI in FIS:
                    elem_1=FI['FI']
                    for elem_2 in elem_1:
                        LE=elem_2['TMC']['LE']
                        PC=elem_2['TMC']['PC']
                        QD=elem_2['TMC']['QD']
                        SHP=elem_2['SHP']
                        CF=elem_2['CF']
                        for elem_3 in CF:
                            FF=elem_3['FF']
                            CN=elem_3['CN']                    
                            JF=elem_3['JF']
                            SP=elem_3['SP']
                            TY=elem_3['TY']
                            l.append([EBU_COUNTRY_CODE,EXTENDED_COUNTRY_CODE,UNITS,DE,LI,PBT,mid,LE,PC,QD,SHP,FF,CN,JF,SP,TY])
        clms=['EBU_COUNTRY_CODE','EXTENDED_COUNTRY_CODE','UNITS','DE','LI','PBT','mid','LE','PC','QD','SHP','FF','CN','JF','SP','TY']                    
        df=pd.DataFrame(l,columns=clms)
        df['PBT']=datetime.datetime.now()
        #print(json.dumps(rws_list, indent=2))
    #     if path_to_save:
    #         if os.path.isfile(path_to_save):
    #             df.to_csv(path_to_save,mode='a+',header=False,index=False)
    #         else:
    #             df.to_csv(path_to_save,mode='w+',index=False)
    #     else:
        return df   

In [9]:
#state='New Castle'
def search(keyword=""):
    endpoint = "search"
    attribute_string = "?keyword="+keyword

    r = get_results(endpoint, attribute_string)
    return r

def get_results( endpoint="", attribute_string=""):
    url_with_attr = geo_code_url+endpoint+attribute_string
    r = requests.get(url_with_attr, auth=HTTPBasicAuth('geocode', 'ZXasqw12'))
    if r.status_code == 200:
        if r.text == "":
            return "nil"
        else:
            return r.json()
    else:
        return r

from requests.auth import HTTPBasicAuth
geo_code_url = "https://opendata-maps.herokuapp.com/api/geocode/"

def get_realtime_data():
    #pos=search(state)
    #bbox_bangalore=pos['result']['results'][0]['geometry']['bounds']


    ori='https://traffic.cit.api.here.com/traffic/6.1/flow.json?bbox='+minlat\
    +'%2C'+minlon+'%3B'+maxlat+'%2C'+maxlon\
    +'&responseattributes=sh,fc&app_code=JX9Bh_OK-4u3zQSHxqjOkA&app_id=C0j2ZeJpgkm71fOJGGzv'


    ori=requests.get(ori)
    
    ori=create_data_1(ori.json())
    return ori

In [15]:
get_realtime_data()

EBU_COUNTRY_CODE EXTENDED_COUNTRY_CODE   UNITS                     DE  \
0                 5                    F2  metric           80 Feet Road   
1                 5                    F2  metric           80 Feet Road   
2                 5                    F2  metric           80 Feet Road   
3                 5                    F2  metric           80 Feet Road   
4                 5                    F2  metric          8th Main Road   
5                 5                    F2  metric          8th Main Road   
6                 5                    F2  metric      Ejipura Main Road   
7                 5                    F2  metric      Ejipura Main Road   
8                 5                    F2  metric      Ejipura Main Road   
9                 5                    F2  metric        Inner Ring Road   
10                5                    F2  metric        Inner Ring Road   
11                5                    F2  metric        Inner Ring Road   
12                5                    F2  metric        Inner Ring Road   
13                5                    F2  metric        Inner Ring Road   
14                5                    F2  metric  Mahayogi Vannama Road   
15                5                    F2  metric  Mahayogi Vannama Road   
16                5                    F2  metric  Mahayogi Vannama Road   

           LI                        PBT  \
0   503-00507 2018-06-19 15:43:31.558100   
1   503-00507 2018-06-19 15:43:31.558100   
2   503+00507 2018-06-19 15:43:31.558100   
3   503+00507 2018-06-19 15:43:31.558100   
4   503-00566 2018-06-19 15:43:31.558100   
5   503+00566 2018-06-19 15:43:31.558100   
6   503-01074 2018-06-19 15:43:31.558100   
7   503+01074 2018-06-19 15:43:31.558100   
8   503+01074 2018-06-19 15:43:31.558100   
9   503-01262 2018-06-19 15:43:31.558100   
10  503-01262 2018-06-19 15:43:31.558100   
11  503+01262 2018-06-19 15:43:31.558100   
12  503+01262 2018-06-19 15:43:31.558100   
13  503+01262 2018-06-19 15:43:31.558100   
14  503-01620 2018-06-19 15:43:31.558100   
15  503-01620 2018-06-19 15:43:31.558100   
16  503+01620 2018-06-19 15:43:31.558100   

                                      mid       LE    PC QD  \
0   d341406a-37f0-4336-944b-6aa588cc4f02|  0.75393   509  +   
1   d341406a-37f0-4336-944b-6aa588cc4f02|  1.08312   508  +   
2   1784b048-466a-4856-b6a2-c8165437e966|  1.06206   509  -   
3   1784b048-466a-4856-b6a2-c8165437e966|  0.73791   510  -   
4   5167d4c4-4f97-4da8-a8fe-466c69b29291|  0.80135   567  +   
5   8b4d7bf9-64ab-4120-ab7a-34ba13762479|  0.74837   568  -   
6   1346f963-6231-4e69-8b07-edd47a73edc4|  2.01739  1075  +   
7   0ab4f8bf-077d-439d-b989-4387893af115|  0.02025  1075  -   
8   0ab4f8bf-077d-439d-b989-4387893af115|  2.00822  1076  -   
9   92bf549d-2419-435c-8286-2a7e547bd949|  2.17689  1264  +   
10  92bf549d-2419-435c-8286-2a7e547bd949|  0.65959  1263  +   
11  2d5e19fa-3488-46cb-83d5-05eda9c30c1d|  0.04593  1263  -   
12  2d5e19fa-3488-46cb-83d5-05eda9c30c1d|  0.61526  1264  -   
13  2d5e19fa-3488-46cb-83d5-05eda9c30c1d|  2.16014  1265  -   
14  c01cd581-588f-47f0-ae12-95eee78b41d0|  0.03263  1627  +   
15  c01cd581-588f-47f0-ae12-95eee78b41d0|  0.32274  1626  +   
16  de6a6276-d443-49cb-85e9-51c81557c9ce|  0.35836  1627  -   

                                                  SHP    FF    CN       JF  \
0   [{'value': ['12.94256,77.62273 12.94217,77.623...  27.0  0.71  6.58902   
1   [{'value': ['12.93009,77.6332 12.92984,77.6332...  32.0  0.71  3.75632   
2   [{'value': ['12.93007,77.63312 12.93019,77.633...  31.0  0.71  8.03029   
3   [{'value': ['12.93728,77.62683 12.93763,77.626...  30.0  0.70  8.24069   
4   [{'value': ['12.92999,77.62925 12.93015,77.629...  27.0  0.71  3.42113   
5   [{'value': ['12.93495,77.62487 12.93486,77.625...  29.0  0.70  5.54009   
6   [{'value': ['12.95163,77.62151 12.95146,77.622...  26.0  0.70  6.17250   
7   [{'value': ['12.93848,77.63273 12.93858,77.632...  25.0  0.70  5.26106   
8   

In [12]:
import requests, json

In [14]:
import pandas as pd